# Generated by Django 5.2.8 on 2026-01-10 15:00

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import users.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('role', models.CharField(blank=True, choices=[('babysitter', 'Babysitter'), ('parent', 'Parent')], max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BabysitterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('characteristics', models.JSONField(blank=True, default=list)),
                ('drivers_license', models.BooleanField(default=False)),
                ('car', models.BooleanField(default=False)),
                ('has_children', models.BooleanField(default=False)),
                ('smoker', models.BooleanField(default=False)),
                ('preferred_babysitting_location', models.CharField(blank=True, choices=[('parents_home', 'Parents Home'), ('babysitters_home', 'Babysitters Home'), ('flexible', 'Flexible')], max_length=50, null=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('experience_with_ages', models.JSONField(blank=True, default=list)),
                ('background_check', models.BooleanField(default=False)),
                ('first_aid_certified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'babysitter'}, on_delete=django.db.models.deletion.CASCADE, related_name='babysitter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Babysitter Profile',
                'verbose_name_plural': 'Babysitter Profiles',
                'db_table': 'babysitter_profiles',
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('apartment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_children', models.IntegerField(blank=True, null=True)),
                ('children_ages', models.JSONField(blank=True, default=list)),
                ('has_special_needs', models.BooleanField(default=False)),
                ('special_needs_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('preferred_babysitting_location', models.CharField(blank=True, choices=[('parents_home', 'Parents Home'), ('babysitters_home', 'Babysitters Home'), ('flexible', 'Flexible')], max_length=50, null=True)),
                ('preferred_languages', models.JSONField(blank=True, default=list)),
                ('preferred_experience_years', models.IntegerField(blank=True, null=True)),
                ('preferred_experience_with_ages', models.JSONField(blank=True, default=list)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('pets_in_home', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parent Profiles',
                'db_table': 'parent_profiles',
            },
        ),
    ]
