# Generated by Django 5.2.8 on 2026-01-10 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('account', '0009_emailaddress_unique_primary_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_confirmation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_attempt', to='account.emailconfirmation')),
            ],
            options={
                'verbose_name': 'Email Verification Attempt',
                'verbose_name_plural': 'Email Verification Attempts',
            },
        ),
    ]
