# Generated by Django 5.2.8 on 2026-01-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverificationattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitterprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from all reviews (1-5)', max_digits=3),
        ),
        migrations.AddField(
            model_name='babysitterprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reviews received'),
        ),
    ]
