# Generated by Django 5.2.8 on 2026-01-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_babysitterprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='formatted_address',
            field=models.CharField(blank=True, help_text='Formatted address from geocoding', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
