# Generated by Django 5.2.8 on 2026-01-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_parentprofile_formatted_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitterprofile',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='babysitterprofile',
            name='formatted_address',
            field=models.CharField(blank=True, help_text='Formatted address from geocoding', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='babysitterprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='babysitterprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='babysitterprofile',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
