# Generated by Django 5.2.8 on 2026-01-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravailability',
            name='whole_day',
            field=models.BooleanField(default=False),
        ),
    ]
