# Generated by Django 5.2.8 on 2026-01-10 15:00

import django.db.models.deletion
import django.utils.timezone
import gen_hub_be.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('whole_day', models.BooleanField(default=False)),
                ('color', models.CharField(default='#0099ff', max_length=32)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('unclaimed', 'Unclaimed'), ('claimed', 'Claimed')], default='unclaimed', max_length=16)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('extra_dates', gen_hub_be.db.fields.FlexibleJSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='categories.category')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
    ]
