# Generated by Django 5.2.8 on 2026-01-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_make_end_duration_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('unclaimed', 'Unclaimed'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unclaimed', max_length=16),
        ),
    ]
