# Generated by Django 5.2.8 on 2026-01-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='color',
        ),
    ]
