# Generated by Django 5.2.8 on 2026-01-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_color_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='formatted_address',
            field=models.CharField(blank=True, help_text='Formatted address from geocoding', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.CharField(blank=True, help_text='Raw address entered by user', max_length=255, null=True),
        ),
    ]
