# Generated by Django 5.2.8 on 2026-01-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_task_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_completed', 'Task Completed'), ('new_review', 'New Review'), ('application_accepted', 'Application Accepted'), ('application_rejected', 'Application Rejected'), ('new_application', 'New Application'), ('custom', 'Custom')], default='custom', max_length=64),
        ),
    ]
